--Table used for CRUD(Users_Info)
CREATE TABLE USERS_INFO (
ID NUMBER GENERATED AS IDENTITY,
NAME VARCHAR2(30) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
COUNTRY VARCHAR2(50) NOT NULL
)

--Table used for login(Users)
CREATE TABLE USERS (
USERNAME VARCHAR2(30) NOT NULL,
PASSWORD VARCHAR2(30) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL
)